### PR TITLE
Add User Class & Home Controller

### PR DESCRIPTION
**Pull request by Kethsar**

### CODE REVIEW

**Comment by Chef-Code** [comment]
This branch has conflicts

**Comment by Chef-Code** [comment]
@Kethsar  So were the conflicts were resolved?

**Comment by Kethsar** [comment]
@Chef-Code yes. The point of peer-reviews are to check the code in the changes. You can more or less ignore if there are conflicts. I'll resolve those as need be.

**Comment by Kethsar** [comment]
In the interest of time, I'll be merging merging this.

**Comment by Chef-Code** [comment]
@Kethsar Yea I know, more of a confirmation statement

**Pull request merged**
