### PR TITLE
Lonnie

### PR DESCRIPTION
**Pull request by Chef-Code**
I added a few different pictures to the image file one being the lcc logo, which I added above the control panel list options. it is responsive

### CODE REVIEW

**Comment by Chef-Code** [comment]
The disable enable coordinators I did not purposefully try to include in this pull request

**Comment by Chef-Code** [comment]
hold on

**Comment by Chef-Code** [comment]
OK now someone can look over it

**Comment by Chef-Code** [comment]
@Kethsar @droopy25 @gafler @BenMiddleton Can I get Some Feed-Back, this has been sitting here for 2 days

**Comment by Kethsar** [comment]
Done. Nice job.

**Pull request merged**
