### PR TITLE
Control Panel nav fix

### PR DESCRIPTION
**Pull request by BenMiddleton**
I hacked together a pop-out menu for small browser sizes.

Also, a few more unit tests.

### CODE REVIEW

**Comment by Kethsar** [comment]
@BenMiddleton when was the last time you merged master? It appears you haven't even merged master since your last pull requested was merged. You should probably do that.

**Comment by Chef-Code** [comment]
This looks good, I'm going to accept this, I think the actual mark up for the view could be updated although.  Check out the code I posted in the Issue tracker regarding this bug, I also added the LCC Logo that appears above all control panel list options

**Comment by Chef-Code** [comment]
@BenMiddleton  I second the suggestion, after you merge this pull request looks good.  I placed code in the issue tracker that you should glance over.  Tell me what you think.  The code also places the LCC logo above the control panel list

**Comment by BenMiddleton** [comment]
I merged master again. Everything should be up to snuff.

**Comment by Kethsar** [comment]
@BenMiddleton I just messed with it a little bit, and have two changes to propose. Or one, since one of them removes the need for the other. 

First, replace padding-top with margin-top in the dashboard.css style sheet for the body tag. It makes the scrollbar actually visible. Instead of this https://my.mixtape.moe/sbcssm.png we see this https://my.mixtape.moe/noxowh.png

Second, add min-height: 768px (or something like that) to the .row-offcanvas-left.active section of the offcanvas.css style sheet. That renders the first suggestion moot since it goes from this https://my.mixtape.moe/gdftre.png to this https://my.mixtape.moe/efmpab.png

EDIT: My screenshots were on Chrome. I see Firefox did not have the second issue. The first suggestion applies to FF as well, though, as the tip of the scroll bar is still hidden.

**Comment by Chef-Code** [comment]
I like the very last  [https://my.mixtape.moe/efmpab.png](https://my.mixtape.moe/efmpab.png) suggestion

**Comment by BenMiddleton** [comment]
I made some more tweaks. (and checked it in 3 browsers)

**Comment by Kethsar** [comment]
Awesome, merging

**Pull request merged**
