### PR TITLE
Account Controller

### PR DESCRIPTION
**Pull request by Kethsar**
Added the account controller
Moved UpdateStudent logic to this controller
Implemented suggestion #94 and #92 
Allow coordinator to edit their e-mail and the majors they coordinate
Implemented suggestion #99

### CODE REVIEW

**Comment by Chef-Code** [comment]
Does the GPA have constraints

**Comment by Chef-Code** [comment]
Can I put my GPA as 16.55

**Comment by Kethsar** [comment]
@Chef-Code true enough, will fix

**Comment by Chef-Code** [comment]
ok

**Comment by Kethsar** [comment]
@Chef-Code Fixed, with the boundaries using this as a guide https://www.lanecc.edu/copps/documents/grades-definitions

There appears to be no minimum requirement unless you are getting a transfer degree or are utilizing financial aid.

**Comment by Chef-Code** [comment]
Sweet, looks good. Nice find in regards to the LCC grade documentation

**Pull request merged**
